//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OjasMart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VendorMaster
    {
        public int Id { get; set; }
        public string VendorCode { get; set; }
        public string StoreName { get; set; }
        public string ContactName { get; set; }
        public string MobileNo { get; set; }
        public string EmailID { get; set; }
        public string StoreLogo { get; set; }
        public Nullable<bool> IsMobileVarified { get; set; }
        public Nullable<bool> IsEmailVarified { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Description { get; set; }
        public string LogisticType { get; set; }
        public string AdharNo { get; set; }
        public string PanNo { get; set; }
        public string GSTNo { get; set; }
        public string bussnessType { get; set; }
        public string bussnessStartDate { get; set; }
        public string MerchantRef { get; set; }
        public Nullable<int> CourierStatus { get; set; }
    }
}
