//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OjasMart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MenuConfiguration
    {
        public int Id { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> MainMenuId { get; set; }
        public Nullable<int> SubMenuId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryBy { get; set; }
        public Nullable<int> ThiredLevelMenuid { get; set; }
    }
}
