//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OjasMart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Login
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public string CompanyCode { get; set; }
        public string EmailAddress { get; set; }
        public string ContactNo { get; set; }
        public Nullable<int> LoginCount { get; set; }
    }
}
