//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OjasMart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MainMenu
    {
        public int Id { get; set; }
        public string MainMenuName { get; set; }
        public string Url { get; set; }
        public Nullable<int> Priority { get; set; }
        public string MenuIcon { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public string AccesibleFor { get; set; }
    }
}
