//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OjasMart.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    public partial class tbl_VendorRegistration
    {
        public int SrNo { get; set; }
        public string VendorId { get; set; }
        public string FrenchiseId { get; set; }
        public string Name { get; set; }
        public string EmailId { get; set; }
        public string ContactNo { get; set; }
        public string FullAddress { get; set; }
        public string ProfitAmount { get; set; }
        public string ApproveStatus { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string GSTNo { get; set; }
        public string MSME { get; set; }
        public string CityName { get; set; }
        public string State { get; set; }
        public string userType { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string OTP { get; set; }
        public string OTPStatus { get; set; }
        public string Locality { get; set; }
        public string Pincode { get; set; }
        public string msg { get; set; }
        public string strId { get; set; }
        public DataTable dt2 { get; set; }

    }
}
